name: ODL Universal Compiler Workflow
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.22'
    
    - name: Init Go Module
      run: go mod init odl || true

    - name: Build the ODL Compiler (odlc)
      run: go build -o odlc compiler.go

    - name: Compile ODL Source to EXE
      env:
        GOOS: windows
        GOARCH: amd64
      run: ./odlc test.odl test_program.exe

    - name: Upload EXE Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Compiled_ODL_Program
        path: test_program.exe
